"""Initial migration

Revision ID: 42d57126ded8
Revises: 
Create Date: 2025-06-25 21:09:35.684724
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '42d57126ded8'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username')
    )
    op.create_table('category',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['user.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('project',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('creator_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['creator_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('due_date', sa.DateTime(), nullable=True),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('assigned_to', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['assigned_to'], ['user.id']),
        sa.ForeignKeyConstraint(['project_id'], ['project.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_category',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('task_id', 'category_id')
    )

    # ✅ Indexes
    op.create_index('idx_users_email', 'user', ['email'])
    op.create_index('idx_users_username', 'user', ['username'])
    op.create_index('idx_projects_creator', 'project', ['creator_id'])
    op.create_index('idx_projects_created_at', 'project', ['created_at'])
    op.create_index('idx_tasks_project', 'task', ['project_id'])
    op.create_index('idx_tasks_assigned_to', 'task', ['assigned_to'])
    op.create_index('idx_tasks_status', 'task', ['status'])
    op.create_index('idx_tasks_due_date', 'task', ['due_date'])
    op.create_index('idx_categories_created_by', 'category', ['created_by'])
    op.create_index('idx_categories_name', 'category', ['name'])
    op.create_index('idx_task_categories_task', 'task_category', ['task_id'])
    op.create_index('idx_task_categories_category', 'task_category', ['category_id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_category')
    op.drop_table('task')
    op.drop_table('project')
    op.drop_table('category')
    op.drop_table('user')
    # ### end Alembic commands ###
